/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial;

import javax.swing.JOptionPane;

/**
 *
 * @author Aljadis Adán
 */
public class Hipotenusa extends javax.swing.JFrame {

    /**
     * Creates new form Hipotenusa
     */
    public Hipotenusa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCatetoO = new javax.swing.JTextField();
        txtCatetoA = new javax.swing.JTextField();
        txtHipotenusa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 340));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ethnocentric", 0, 14)); // NOI18N
        jLabel1.setText("   Calcular Hipotenusa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 300, 20);

        jLabel2.setFont(new java.awt.Font("Ethnocentric", 2, 14)); // NOI18N
        jLabel2.setText("Cateto opuesto (cm):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 250, 16);

        jLabel3.setFont(new java.awt.Font("Ethnocentric", 2, 14)); // NOI18N
        jLabel3.setText("Cateto adyacente (cm):");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 130, 270, 16);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Hipotenusa:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 180, 90, 17);
        getContentPane().add(txtCatetoO);
        txtCatetoO.setBounds(170, 100, 70, 20);
        getContentPane().add(txtCatetoA);
        txtCatetoA.setBounds(170, 150, 70, 20);
        getContentPane().add(txtHipotenusa);
        txtHipotenusa.setBounds(130, 200, 160, 20);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 230, 100, 23);

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 260, 100, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
    

        double Hipotenusa;
        double dato = Double.parseDouble(txtCatetoO.getText());
        double dato1 = Double.parseDouble(txtCatetoA.getText());
        Procesos Calcular = new Procesos();
        Hipotenusa = Calcular.Calcular_Hipotenusa(dato, dato1);
        txtHipotenusa.setText(String.valueOf(Hipotenusa));
}
catch(NumberFormatException e){
    JOptionPane.showMessageDialog(null, "Ingrese un número válido.","Algo salió mal.", JOptionPane.WARNING_MESSAGE);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtCatetoO.setText(" ");
        txtCatetoA.setText(" ");
        txtHipotenusa.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hipotenusa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hipotenusa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCatetoA;
    private javax.swing.JTextField txtCatetoO;
    private javax.swing.JTextField txtHipotenusa;
    // End of variables declaration//GEN-END:variables
}
